[package]
name = "tp-xcm-core-buyer"
authors = [ "Moondance Labs" ]
description = "XCM Core Buyer Primitives"
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }
parity-scale-codec = { version = "3.0.0", default-features = false, features = [ "derive", "max-encoded-len" ] }
scale-info = { version = "2.10.0", default-features = false }
sp-keystore = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }
sp-std = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }
tp-traits = { path = "../traits", default-features = false }

[features]
default = [ "std" ]
std = [
	"frame-support/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"sp-keystore/std",
	"sp-runtime/std",
	"sp-std/std",
	"tp-traits/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"tp-traits/runtime-benchmarks",
]
