[package]
name = "pallet-xcm-core-buyer-runtime-api"
authors = [ "Moondance Labs" ]
description = "Runtime api for xcm-core-buyer runtime api"
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[lints]
workspace = true

[dependencies]
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }
pallet-xcm-core-buyer = { path = "../../xcm-core-buyer", default-features = false }
parity-scale-codec = { version = "3.0.0", default-features = false, features = [ "derive", "max-encoded-len" ] }
scale-info = { version = "2.10.0", default-features = false }
serde = { version = "1.0.197", default-features = false, optional = true, features = [ "derive" ] }
sp-api = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }
sp-consensus-slots = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }
sp-std = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }
thiserror = { version = "2.0.12", optional = true }
tp-xcm-core-buyer = { path = "../../../primitives/xcm-core-buyer", default-features = false }

[features]
default = [ "std" ]
std = [
	"frame-support/std",
	"pallet-xcm-core-buyer/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"serde",
	"serde?/std",
	"sp-api/std",
	"sp-consensus-slots/std",
	"sp-runtime/std",
	"sp-std/std",
	"thiserror",
	"tp-xcm-core-buyer/std",
]
runtime-benchmarks = [ "pallet-xcm-core-buyer/runtime-benchmarks" ]
