[package]
name = "tp-traits"
authors = [ "Moondance Labs" ]
description = "Tanssi primitive traits"
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
dp-chain-state-snapshot = { git = "https://github.com/OpenZeppelin/dancekit", branch = "polkadot-branch-stable2412", default-features = false }
dp-container-chain-genesis-data = { git = "https://github.com/OpenZeppelin/dancekit", branch = "polkadot-branch-stable2412", default-features = false }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }
impl-trait-for-tuples = "0.2.2"
macro_rules_attribute = { version = "0.2.0" }
parity-scale-codec = { version = "3.0.0", default-features = false, features = [ "derive", "max-encoded-len" ] }
scale-info = { version = "2.10.0", default-features = false }
serde = { version = "1.0.197", default-features = false }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }
sp-std = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }

# Cumulus
cumulus-primitives-core = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2503", default-features = false }

[features]
default = [ "std" ]
std = [
	"cumulus-primitives-core/std",
	"dp-chain-state-snapshot/std",
	"dp-container-chain-genesis-data/std",
	"frame-support/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"serde/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
